services:
  app:
    build: .
    container_name: menuger_app
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://admin:adminpassword@postgres:5432/menuger
      - REDIS_URL=redis://redis:6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - menuger_network

  postgres:
    image: postgres:15
    container_name: postgres_menuger
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: menuger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d menuger"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - menuger_network

  redis:
    image: redis:7-alpine
    container_name: redis_menuger
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - menuger_network

networks:
  menuger_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
